version: "3.8"
services:
  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - scrapper-app
    depends_on:
      - server

  server:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    hostname: api
    networks:
      - scrapper-app
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    hostname: selenium
    networks:
      - scrapper-app


networks:
  scrapper-app:
    driver: bridge
