version: "3.8"
services:
  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - CADDYFILE=Caddyfile
    stdin_open: true
    ports: 
      - "80:80"
    networks:
      - scrapper-app
    depends_on:
      - server
    volumes:
    - caddy-data:/data
    - caddy-config:/config


  server:
    container_name: server
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    hostname: server
    networks:
      - scrapper-app
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    hostname: selenium
    networks:
      - scrapper-app

networks:
  scrapper-app:
    driver: bridge

volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local