version: "3.8"
services:
  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - scrapper-app
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    hostname: scrapper
    networks:
      - scrapper-app
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    hostname: selenium
    networks:
      - scrapper-app

  nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      container_name: nginx
      hostname: nginx
      ports:
        - "80:80" 
      depends_on:
        - server
      networks:
        - scrapper-app


networks:
  scrapper-app:
    driver: bridge
