"""empty message

Revision ID: 74047c90e241
Revises: 
Create Date: 2022-09-11 04:02:19.096251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74047c90e241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_details', sa.Column('video_link', sa.String(), nullable=True))
    op.drop_column('video_details', 'video_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_details', sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('video_details', 'video_link')
    # ### end Alembic commands ###
